name: adhan_dart
version: 1.2.0
description: >-
    Library to calculate prayer times for muslims.
    Based on precise astronomical formula.
homepage: https://github.com/prayer-timetable/adhan_dart/
documentation: https://github.com/prayer-timetable/adhan_dart/
environment:
    sdk: '>=2.19.0  <4.0.0'
dependencies:

dev_dependencies:
    timezone: ^0.10.1
    flutter_lints: ^6.0.0
